### ISSUE TITLE
No feedback after post is added

### ISSUE THREAD

**Issue by hthoma20** [upcs/cs-341-project-sq19-hotel#64]
Steps to recreate:
1) Login
2) Navigate to Computer Science
3) Navigate to Anaysis of Algorithms
4) Add post
5) Enter iformation

Then I got a popup saying post has been created, but the post did not appear.
Refreshing did not help.
After navigating back to home, then navigating back to the course, the post was there.

**Comment by Lexden12** [comment]
You need to be logged in to create anything. Unfortunately, although it is supposed to give feedback about that, it errors out. That will be something important for us to fix, thanks!

**Comment by Lexden12** [comment]
Patched to provide a notification that you must be logged in.
