### ISSUE TITLE
Course Creation Fails to Update

### ISSUE THREAD

**Issue by Katacka** [upcs/cs-341-project-sq19-hotel#65]
Steps to recreate:
1. Visit http://35.192.235.243:3000/
2. Click on 'Business'
3. Click 'Create a New Class'
4. Enter arbitrary input
5. Observe that the class has not been created
6. Similarly, when attempting to create another course recognize the input screen does not update 

I question whether write permissions exist on the database as I tried some friendly injections which did not work (and I don't imagine excessive security exists at this point).

**Comment by Lexden12** [comment]
Unfortunately, this is because you need to be signed in to add any courses or posts or comments. This will be made clearer in the future. Thanks!

**Comment by Lexden12** [comment]
Patched to provide a notification that you must be logged in.
