### ISSUE TITLE
Cannot add comment to post

### ISSUE THREAD

**Issue by hthoma20** [upcs/cs-341-project-sq19-hotel#66]
Steps to recreate:
1) navigate to a post (Computer Science -> Algorithms -> help on hw11)
2) Click add comment
3) Write comment
4) Click "add comment"

Then it says "Comment submitted". However, I could not see any comment. Even after going home and renavigating.

Other info:
16105830 was the post-placeholder number

**Comment by Lexden12** [comment]
Unfortunately, that is still the problem of needing to be signed in.

**Comment by vogtl19** [comment]
We will be adding a notification so you cannot post/comment without logging in or signing up so it is more clear.

**Comment by Lexden12** [comment]
Patched to provide a notification that you must be logged in.
