### ISSUE TITLE
Login redirects to home page

### ISSUE THREAD

**Issue by crawforl20** [upcs/cs-341-project-sq19-hotel#67]
After creating an account by signing up.
And logging in to the account.
Change in text says user have been successfully logged in, however there is no change until I refresh the page.  

Enhancement: After successfully logging in, redirect user to homepage.

**Comment by Lexden12** [comment]
That is a good idea, thanks!

**Comment by Lexden12** [comment]
Patched. After logging in, redirects to homepage.
