### ISSUE TITLE
CSS issue

### ISSUE THREAD

**Issue by gannotsk21** [upcs/cs-341-project-sq19-hotel#69]
The text box for adding a new post is outside of the popup box.

**Comment by gannotsk21** [comment]
wait. that was just on mine lol

**Comment by Lexden12** [comment]
This could be a zoom-level/screen resolution problem. Either way, something to fix! Thank you!

**Comment by vogtl19** [comment]
We have revamped our CSS and it seems to be fixed! Thank you
