### ISSUE TITLE
Creating a new course 

### ISSUE THREAD

**Issue by schibel21** [upcs/cs-341-project-sq19-hotel#70]
When creating a new course, the only buttons that appear along with the "You have submitted a course" are "cancel" and "submit course".
1.) Went to English page 
2.) Created new course for English
3.) Said I submitted a course
4.) Was not sure what to click when making sure that my course was validated because "cancel" has connotations that the course is going to be cancelled and "submit course" makes it seem like I'm going to submit the course again and clicking the x in the top right hand corner makes it seem like I never submitted it at all. 

I would just suggest having a "done" button once you've submitted the course name rather then the two that are there.

**Comment by Lexden12** [comment]
Unfortunately, if you are not logged in, the validator errors out which means we can't update the text. In reality, you need to be logged in to do anything :)

**Comment by Lexden12** [comment]
Patched to provide a notification that you must be logged in.
