### ISSUE TITLE
I created an account and couldn't log in

### ISSUE THREAD

**Issue by itschrisL** [upcs/cs-341-project-sq19-hotel#71]
I created an account on the sign up tab but when I went to log back in the log in button didn't do anything.

**Comment by huangjo20** [comment]
We replicated it with signup info "email: qwerty@up.edu, username: qwerty, password: qwerty", and it appears to work. Did you make sure to login using the email and password, instead of the username? Thanks!

**Comment by Lexden12** [comment]
Yeah, if you do not input a valid email it will not even try to validate your account. I could add an alert just like in signup.

**Comment by Lexden12** [comment]
Alert appears when email is not of proper format or password is empty.
